# coding: utf-8
import pybullet as p
p.connect(p.GUI)
floor_shape = p.createCollisionShape(p.GEOM_PLANE)
floor = p.createMultiBody(floor_shape, floor_shape)
box_shape = p.createCollisionShape(p.GEOM_BOX, halfExtents=[1,1,1])
box = p.createMultiBody(box_shape, box_shape)
p.setGravity(0,0,-10)
p.setRealtimeSimulation(1)
p.setRealTimeSimulation(1)
import pybullet_data as pd
pd.getDataPath()
robot = p.loadURDF(pd.getDataPath() + '/soccerball.urdf')
robot = p.loadURDF(pd.getDataPath() + '/r2d2.urdf')
rob1 = p.loadURDF('first.urdf')
get_ipython().run_line_magic('more', 'first.urdf')
rob1 = p.loadURDF('first.urdf')
p.setPhysicsEngineParameter(enableFileCaching=0)
rob1 = p.loadURDF('first.urdf')
p.setJountMotorControl2(rob1, 0, controlMode=p.VELOCITY_CONTROL, targetVelocity=1)
p.setJointMotorControl2(rob1, 0, controlMode=p.VELOCITY_CONTROL, targetVelocity=1)
p.setJointMotorControl2(rob1, 0, controlMode=p.VELOCITY_CONTROL, targetVelocity=100000)
rob1 = p.loadURDF('first.urdf')
p.setJointMotorControl2(rob1, 0, controlMode=p.VELOCITY_CONTROL, targetVelocity=100000)
rob1 = p.loadURDF('first.urdf')
p.setJointMotorControl2(rob1, 0, controlMode=p.VELOCITY_CONTROL, targetVelocity=1)
p.setJointMotorControl2(rob1, 0, controlMode=p.VELOCITY_CONTROL, targetVelocity=2)
